
CREATE DATABASE workoutbuddy_db;
USE workoutbuddy_db;

CREATE TABLE USER (
  user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(15) NOT NULL,
  buddy_name VARCHAR(45) NOT NULL,
  email VARCHAR(30) NOT NULL,
  gender CHAR(1) CHECK(gender IN ('M', 'F', 'O', 'N'))
);

CREATE TABLE WORKOUT (
  workout_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  workout_name VARCHAR(30) NOT NULL
);

CREATE TABLE GYM (
  gym_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  gym_name VARCHAR(15) NOT NULL
);

CREATE TABLE CITY (
  city_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  city_name VARCHAR(30) NOT NULL
    
);

CREATE TABLE PROFILEPIC (
  profile_pic_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  image_url VARCHAR(255) NOT NULL,
 FOREIGN KEY (user_id) REFERENCES USER(user_id)
);
