
CREATE DATABASE workoutbuddy_db;
USE workoutbuddy_db;

CREATE TABLE USER (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(15) NOT NULL,
  buddy_name VARCHAR(45) NOT NULL,
  email VARCHAR(30) NOT NULL,
  gender CHAR(1) CHECK(gender IN ('M', 'F', 'O', 'N'))
);

CREATE TABLE WORKOUT (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  workout_name VARCHAR(30) NOT NULL    
);

CREATE TABLE GYM (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  gym_name VARCHAR(15) NOT NULL,
);

CREATE TABLE CITY (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  city_name VARCHAR(30) NOT NULL
    
);